[workspace]
members = [
    "genet-kernel",
    "genet-filter",
    "genet-sdk",
    "genet-derive",
    "genet-abi",
    "genet-napi"
]
exclude = ["package"]

[replace]
"genet-abi:0.5.0" = { path = "./genet-abi" }
"genet-sdk:0.5.0" = { path = "./genet-sdk" }
